#ifndef _CONSTANT_H_
#define _CONSTANT_H_

// Programmer: Hongrui Liu, Mar 14 2021. 
// This is the header file for constant integers.
const int
MIN_COLOR = 0,  MAX_COLOR = 255, MAX_DIMENSION = 2000, MIN_DIMENSION = 0,
MAX_MSG_VALUE = 7, MIN_MSG_VALUE = 0, ENCODE_IMAGE = 1, DECODE_IMAGE = 2, 
WRITE_IMAGE = 3, EXIT_PROGRAM = 4, BLACK = 0, RED = 1, GREEN = 2, BLUE = 3, 
WHITE = 4, YELLOW = 5, MAGENTA = 6, CYAN = 7, USAGE_STATEMENT = 2, 
FILE_ERROR = 3, HEADER_ERROR = 3, MAGIC_ERROR = 3, SIZE_ERROR = 3, 
MAX_COLOR_ERROR = 3, DATA_TYPE_ERROR = 3, OUT_RANGE_ERROR = 3, 
AMOUNT_ERROR = 3, IGNORE_LENGTH = 200, NORMAL_RETURN_VALUE = 0,
CORRECT_INPUT = 2, SECOND_ITEM = 1, FIRST_ITEM = 0;

#endif
